spring.application.name=SOA_News
server.port=9094

spring.datasource.url=jdbc:postgresql://localhost:5432/SOA_News
spring.datasource.username=chadi
spring.datasource.password=chedikouissi2004
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Swagger OpenAPI Configuration
springdoc.api-docs.enabled=true
springdoc.api-docs.path=/v3/api-docs
springdoc.swagger-ui.path=/swagger-ui.html
springdoc.swagger-ui.enabled=true
springdoc.swagger-ui.operationsSorter=method
springdoc.default-consumes-media-type=application/json
springdoc.default-produces-media-type=application/json
#api_key=9d88edf4f9f24daa8143f4ee1223c158



# News API Configuration
news.api.key=9d88edf4f9f24daa8143f4ee1223c158
news.api.url=https://newsapi.org/v2